server:
  port: 8761

spring:
  boot:
    admin:
      client:
        url: http://35.237.182.53:9000
        instance:
          prefer-ip: true
  kafka:
    bootstrap-servers: http://35.237.201.4:9092
  zipkin:
    sender:
      type: kafka
  sleuth:
    messaging:
      kafka:
        enabled: true
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 10